### PR TITLE
strptime bug workaround

### PR DESCRIPTION
**Pull request by JDRIVO**
https://bugs.python.org/issue27400

### CODE REVIEW

**Comment by micahg** [comment]
lgtm. TY.

**Comment by JDRIVO** [comment]
Hello micahg, are you able to make a request to have the current version in the Kodi repo be updated?

**Comment by robweber** [comment]
@micahg - I can do it too if you'd like. Just let me know.

**Comment by micahg** [comment]
Yeah, if you have the capacity I'd really appreciate it if you could. Sorry :(

**Comment by robweber** [comment]
Done. https://github.com/xbmc/repo-scripts/pull/2530

**Comment by JDRIVO** [comment]
Cheers gentlemen.

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Pull request merged**
