### PR TITLE
Fixed import command. Changed exception clause to newer python version.

### PR DESCRIPTION
**Pull request by SchapplM**
Just noticed this when testing the fixed watchedlist/dropbox-integration.

### CODE REVIEW

**Comment by micahg** [comment]
Are you sure? My test client and my tests in watchedlist did not require this -- i'm concerned this is going to break what is already working.

**Comment by SchapplM** [comment]
I tested this on two machines (both Ubuntu 14.04 with Kodi 17.6).
When I try the authentification without my changes, I get:

> 22:53:09.823 T:140331806877440   DEBUG: CPythonInvoker(14, /home/schappler/.kodi/addons/script.module.dropbox/authenticate.py): start processing
> 22:53:09.899 T:140331806877440   DEBUG: -->Python Interpreter Initialized<--
> 22:53:09.899 T:140331806877440   DEBUG: CPythonInvoker(14, /home/schappler/.kodi/addons/script.module.dropbox/authenticate.py): the source file to load is "/home/schappler/.kodi/addons/script.module.dropbox/authenticate.py"
> 22:53:09.899 T:140331806877440   DEBUG: CPythonInvoker(14, /home/schappler/.kodi/addons/script.module.dropbox/authenticate.py): setting the Python path to /home/schappler/.kodi/addons/script.module.dropbox:/home/schappler/.kodi/addons/script.module.certifi/lib:/home/schappler/.kodi/addons/script.module.chardet/lib:/home/schappler/.kodi/addons/script.module.idna/lib:/home/schappler/.kodi/addons/script.module.qrcode/lib:/home/schappler/.kodi/addons/script.module.requests/lib:/home/schappler/.kodi/addons/script.module.six/lib:/home/schappler/.kodi/addons/script.module.urllib3/lib:/usr/share/kodi/addons/script.module.pil/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client:/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
> 22:53:09.899 T:140331806877440   DEBUG: CPythonInvoker(14, /home/schappler/.kodi/addons/script.module.dropbox/authenticate.py): entering source directory /home/schappler/.kodi/addons/script.module.dropbox
> 22:53:09.899 T:140331806877440   DEBUG: CPythonInvoker(14, /home/schappler/.kodi/addons/script.module.dropbox/authenticate.py): instantiating addon using automatically obtained id of "script.module.dropbox" dependent on version 2.25.0 of the xbmc.python api
> 22:53:09.913 T:140331806877440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.ImportError'>
>                                             Error Contents: No module named dropbox.exceptions
>                                             Traceback (most recent call last):
>                                               File "/home/schappler/.kodi/addons/script.module.dropbox/authenticate.py", line 10, in <module>
>                                                 from dropbox.exceptions import AuthError
>                                             ImportError: No module named dropbox.exceptions
>                                             -->End of Python script error report<--

I tried by going to watchedlist->settings->database->dropbox authorization code
By doing this, the authentificate.py is started.

The error seems reasonable to me, since for the script authentificate.py the path is `lib.dropbox` since it is the dropbox addon itself. Other addons only use `dropbox` as path because they include the dropbox API with `<import addon="script.module.dropbox" version="8.4.0"/>` which goes directly to the lib directory.

**Comment by micahg** [comment]
I've brought these changes over and they seem to work fine for me as well...

Did you have to update the includes in watchdlist.py accordingly? I'll be honest -- I'm confused why its causing you problems but not me.

**Comment by micahg** [comment]
Hey @SchapplM - I've been working on trying to recreate this and I see you've already fixed some issues with my original PR -- thanks for that (and sorry).

I'm a bit reluctant to merge this though as I still cannot reproduce it -- that being said, if you are positive this is required, I'll release a new version as in my environment (just Ubuntu with Kodi nightly) either way works fine.

I'll request a pull for 8.4.1 tomorrow night if you are sure.

**Comment by SchapplM** [comment]
I will try this with another Kodi setup on a Windows machine.
Since we pushed the addon updates to the krypton (v17) branch, they should work there as well.
Do you use the leia (v18) nightly? Perhaps this could explain the difference.

> Did you have to update the includes in watchdlist.py accordingly? I'll be honest -- I'm confused why its causing you problems but not me.

This pull request does not affect the watchedlist.py, since the script authenticate.py is only called when changing the addon settings via the settings dialog. This happens with `<setting id="dropbox_apikey" type="action" label="30023" action="RunScript(script.module.dropbox, service.watchedlist, dropbox_apikey, bhd2v8hgsmqwcgt, t2cepoevjqyubnd)" enable="eq(-1,true)" />` in settings.xml of the watchedlist addon via `<extension point="xbmc.python.library" library="authenticate.py">` of addon.xml of the dropbox addon.
Did you try to reproduce this the way I described?

**Comment by micahg** [comment]
Indeed - I'm on Leia. I'll grab a v17 build when I get a chance...

**Comment by micahg** [comment]
Hello. On a local build of Kodi 17.6 (still Ubuntu) it works. I'll boot into windows and give it a go there...

**Pull request merged**
